# Generated by Django 2.2.24 on 2022-12-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_text',
            field=models.TextField(blank=True, verbose_name='Текст жалобы:'),
        ),
    ]
